[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "vigil"
version = "0.1.0"
description = "Open Source Vulnerability Assessment Framework"
requires-python = ">=3.10"

dependencies = [
    "rich"
]

[project.scripts]
vigil = "main:main"

[tool.setuptools]
py-modules = ["main", "config"]

[tool.setuptools.packages.find]
include = ["core*", "ui*"]
